#!/usr/bin/env bash 

echo "-- delete-object"

# Exit immediately if any command returns a non-zero status
set -e 

# check if bucket name is provided 
if [ -z "$1" ]; then
  echo "No bucket name provided. eg: './bucket <bucket-name>'"
  exit 1
fi

BUCKET_NAME=$1

# Step 1: List objects
aws s3api list-objects --bucket $BUCKET_NAME --query 'Contents[].{Key: Key}' --output json > objects.json

# Step 2: Transform the output
jq '{Objects: .}' objects.json > delete.json

# Step 3: Delete objects
aws s3api delete-objects --bucket $BUCKET_NAME --delete file://delete.json

# Clean up
rm objects.json delete.json
