#!/usr/bin/env bash 

echo "-- delete-object"

# Exit immediately if any command returns a non-zero status
set -e 

# check if bucket name is provided 
if [ -z "$1" ]; then
  echo "No bucket name provided. eg: './bucket <bucket-name>'"
  exit 1
fi

BUCKET_NAME=$1

$(aws s3api list-objects-v2 --bucket $BUCKET_NAME) 

aws s3api delete-objects --bucket $BUCKET_NAME --delete 