#!/usr/bin/env bash 

echo "-- list buckets"

# list buckets by creation date in descending order 
aws s3api list-buckets | jq -r '.Buckets | sort_by(.CreationDate) | reverse | .[] | "Bucket: \(.Name) \(.CreationDate)"'
