#!/usr/bin/env bash 

echo "-- put-object"

# check if bucket name is provided 
if [ -z "$1" ]; then
  echo "No bucket name provided. eg: './bucket <bucket-name>'"
  exit 1
fi

# check if filename prefix is provided 
if [ -z "$2" ]; then
  echo "No filename provided. eg: './bucket <bucket-name> <filename>'"
  exit 1
fi

BUCKET_NAME=$1
FILENAME=$2

OBJECT_KEY=$(basename "$FILENAME")

aws s3api put-object \
--bucket $BUCKET_NAME \
--body $FILENAME \
--key $OBJECT_KEY